// Autogenerated from Pigeon (v25.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object NativeApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class ToastDuration(val raw: Int) {
  SHORT(0),
  LONG(1);

  companion object {
    fun ofRaw(raw: Int): ToastDuration? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Données des stats de logs
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class LogStatsData (
  val totalFiles: Long,
  val totalSizeBytes: Long,
  val oldestLogDate: String? = null,
  val newestLogDate: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LogStatsData {
      val totalFiles = pigeonVar_list[0] as Long
      val totalSizeBytes = pigeonVar_list[1] as Long
      val oldestLogDate = pigeonVar_list[2] as String?
      val newestLogDate = pigeonVar_list[3] as String?
      return LogStatsData(totalFiles, totalSizeBytes, oldestLogDate, newestLogDate)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      totalFiles,
      totalSizeBytes,
      oldestLogDate,
      newestLogDate,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is LogStatsData) {
      return false
    }
    if (this === other) {
      return true
    }
    return NativeApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class NativeApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ToastDuration.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LogStatsData.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ToastDuration -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is LogStatsData -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface NativeApi {
  /**
   *
   * Starts the floating volume service.
   * This method starts the android service that manages the floating volume widget.
   *
   */
  fun startService(callback: (Result<Unit>) -> Unit)
  /**
   *
   * Stops the floating volume service.
   * This method stops the android service that manages the floating volume widget.
   *
   */
  fun stopService(callback: (Result<Unit>) -> Unit)
  /**
   *
   * Hides the floating volume widget.
   * This method hides the floating volume widget, but does not stop the service.
   *
   */
  fun hideFloatingVolume(callback: (Result<Unit>) -> Unit)
  /**
   *
   * Shows the floating volume widget.
   * This method shows the floating volume widget, if it is hidden.
   *
   */
  fun showFloatingVolume(callback: (Result<Unit>) -> Unit)
  /**
   *
   * Changes the maximum volume level.
   *
   */
  fun setMaxVolume(maxVolume: Long, callback: (Result<Unit>) -> Unit)
  /**
   *
   * Changes the minimum volume level.
   *
   */
  fun setMinVolume(minVolume: Long, callback: (Result<Unit>) -> Unit)
  /**
   *
   * Show a toast
   *
   */
  fun showToast(message: String, duration: ToastDuration, callback: (Result<Unit>) -> Unit)
  /**
   *
   * Configure si le service doit redémarrer automatiquement au boot
   *
   */
  fun setAutoStartEnabled(enabled: Boolean, callback: (Result<Unit>) -> Unit)
  /**
   *
   * Récupère l'état de l'auto-start
   *
   */
  fun getAutoStartEnabled(callback: (Result<Boolean>) -> Unit)
  /**
   *
   * Définit le délai avant démarrage automatique (en millisecondes)
   *
   */
  fun setAutoStartDelay(delayMs: Long, callback: (Result<Unit>) -> Unit)
  /**
   *
   * Récupère le délai d'auto-start (en millisecondes)
   *
   */
  fun getAutoStartDelay(callback: (Result<Long>) -> Unit)
  /**
   *
   * Configure si l'état du service doit être restauré après boot
   *
   */
  fun setRestoreServiceState(enabled: Boolean, callback: (Result<Unit>) -> Unit)
  /**
   *
   * Récupère l'état du restore
   *
   */
  fun getRestoreServiceState(callback: (Result<Boolean>) -> Unit)
  /**
   *
   * Exporte les logs et retourne l'Intent de partage
   *
   */
  fun exportLogsAndShare(callback: (Result<Unit>) -> Unit)
  /**
   *
   * Efface tous les logs
   *
   */
  fun clearAllLogs(callback: (Result<Unit>) -> Unit)
  /**
   *
   * Récupère les statistiques des logs
   *
   */
  fun getLogStats(callback: (Result<LogStatsData>) -> Unit)
  fun hasNotificationAccess(callback: (Result<Boolean>) -> Unit)
  fun requestNotificationAccess(callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by NativeApi. */
    val codec: MessageCodec<Any?> by lazy {
      NativeApiPigeonCodec()
    }
    /** Sets up an instance of `NativeApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: NativeApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.floating_volume.NativeApi.startService$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.startService{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NativeApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(NativeApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.floating_volume.NativeApi.stopService$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.stopService{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NativeApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(NativeApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.floating_volume.NativeApi.hideFloatingVolume$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.hideFloatingVolume{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NativeApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(NativeApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.floating_volume.NativeApi.showFloatingVolume$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.showFloatingVolume{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NativeApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(NativeApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.floating_volume.NativeApi.setMaxVolume$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val maxVolumeArg = args[0] as Long
            api.setMaxVolume(maxVolumeArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NativeApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(NativeApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.floating_volume.NativeApi.setMinVolume$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val minVolumeArg = args[0] as Long
            api.setMinVolume(minVolumeArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NativeApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(NativeApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.floating_volume.NativeApi.showToast$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val messageArg = args[0] as String
            val durationArg = args[1] as ToastDuration
            api.showToast(messageArg, durationArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NativeApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(NativeApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.floating_volume.NativeApi.setAutoStartEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val enabledArg = args[0] as Boolean
            api.setAutoStartEnabled(enabledArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NativeApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(NativeApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.floating_volume.NativeApi.getAutoStartEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getAutoStartEnabled{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NativeApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NativeApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.floating_volume.NativeApi.setAutoStartDelay$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val delayMsArg = args[0] as Long
            api.setAutoStartDelay(delayMsArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NativeApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(NativeApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.floating_volume.NativeApi.getAutoStartDelay$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getAutoStartDelay{ result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NativeApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NativeApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.floating_volume.NativeApi.setRestoreServiceState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val enabledArg = args[0] as Boolean
            api.setRestoreServiceState(enabledArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NativeApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(NativeApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.floating_volume.NativeApi.getRestoreServiceState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getRestoreServiceState{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NativeApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NativeApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.floating_volume.NativeApi.exportLogsAndShare$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.exportLogsAndShare{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NativeApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(NativeApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.floating_volume.NativeApi.clearAllLogs$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.clearAllLogs{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NativeApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(NativeApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.floating_volume.NativeApi.getLogStats$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getLogStats{ result: Result<LogStatsData> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NativeApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NativeApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.floating_volume.NativeApi.hasNotificationAccess$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.hasNotificationAccess{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NativeApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NativeApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.floating_volume.NativeApi.requestNotificationAccess$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.requestNotificationAccess{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NativeApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(NativeApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Action à envoyer au lecteur multimédia ("play", "pause", "next", "prev")
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface MediaApi {
  fun sendMediaAction(action: String, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by MediaApi. */
    val codec: MessageCodec<Any?> by lazy {
      NativeApiPigeonCodec()
    }
    /** Sets up an instance of `MediaApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: MediaApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.floating_volume.MediaApi.sendMediaAction$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val actionArg = args[0] as String
            api.sendMediaAction(actionArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NativeApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(NativeApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
